### ISSUE TITLE
Missing libraries when opening Komar Eagle Files

### ISSUE THREAD

**Issue by m1kelyons** [Zubax/Komar#24]
Replication: commit 40c347241056

1. Open Komar.sch and Komar.brd in Autodesk Fusion 360 2.0.10253 (subscription) or Eagle 9.6.2 on Win 10 (21390)

Result: Libraries fail to download (see attached).

![Komar_missing_libraries](https://user-images.githubusercontent.com/7957427/122181558-51c39b00-ce3e-11eb-9bb3-095a4bfe4163.png)

**Comment by j3qq4hch** [comment]
These warnings are caused by the fact that Zubax is not using the default Eagle libraries in its work as they are known to be ugly and defective. Although the libraries are not available completely, you can still export all the components involved in the project to a separate library and then use it at your will. 
Please, check [this link](https://forums.autodesk.com/t5/eagle-forum/creating-a-library-from-schematic/td-p/8139804#:~:text=You%20can%20export%20all%20the,Export%20Libraries%20%3E%20Export%20original%20libraries.&text=From%20here%20you%20can%20select,the%20parts%20in%20the%20board.) for more details.
